# Enchanting Overhauled Configuration

# [ENCHANTING_TABLE]
# Whether or not trying to activate the altar with a book causes a violent explosion.
general.enchanting_table.arcane_retribution=true
# Whether activating the enchanting altar should be spectacular or mundane.
general.enchanting_table.activation_effects=true
# Whether the default enchanting table can be mined or instead drops its tome.
general.enchanting_table.mineable_enchanting_table=false
# How many enchantments are skipped when pressing the navigation buttons.
general.enchanting_table.scroll_step=3

# [ANVIL]
# The maximum repair item cost for an item.
general.anvil.max_item_repair_cost=4
# Durability bonus (as percentage) added when combining damaged items.
general.anvil.item_repair_bonus=12
# Chance for the anvil to take damage on use.
general.anvil.anvil_break_chance=0.12

# [DAMAGE_CALCULATION]
# The maximum effective points you can get from enchantments.
general.damage_calculation.protection_numerator=30.0
# The value used to calculate damage reduction.
general.damage_calculation.protection_denominator=40.0


# [GENERAL]

# [GENERAL]
# Whether the max level of scalable enchantments should be overridden by the "enchantment_max_level" value.
enchantment.general.override_enchantment_max_level=true
# The maximum level an enchantment can be *naturally* obtained at.
enchantment.general.enchantment_max_level=3
# The maximum amount of enchantments an Item can entertain.
enchantment.general.max_enchantment_amount=3
# Whether enchanted tomes can contain enchantments of a higher level than naturally possible.
enchantment.general.tomes_have_greater_enchantments=true

# [ENCHANTMENT_TOOLTIP]
# Whether Enchanting Overhauled is allowed to change the appearance of enchantment tooltips in any way, shape or form.
enchantment.enchantment_tooltip.enable_tooltip_modifications=true
# Whether the enchantment name coloring modifications should be applied or not.
enchantment.enchantment_tooltip.name_color_modifications=true
# Whether the enchantment level coloring modifications should be applied or not.
enchantment.enchantment_tooltip.level_color_modifications=true
# Whether the enchantment tooltip block should have a header spelling either "Applied Enchantments" or "Stored Enchantments".
enchantment.enchantment_tooltip.show_enchantment_tooltip_header=true
# Whether enchantments descriptions should be displayed on the items tooltip.
enchantment.enchantment_tooltip.show_tooltip_enchantment_descriptions=true
# Whether enchantments descriptions should displayed on the enchantment slot's tooltip.
enchantment.enchantment_tooltip.show_table_enchantment_descriptions=true


# [ENCHANTMENT]

# [GENERAL]
# Whether the XP requirement formula changes are applied or not.
xp.general.enable_xp_and_level_modifications=true
# XP requirement growth factor.
xp.general.xp_growth_factor=1
# Size of XP level brackets for growth calculation.
xp.general.xp_level_bracket_size=2
# Initial XP requirement value (Y-offset).
xp.general.xp_growth_initial_value=2
# Whether the player xp level should have a defined maximum or be unbound.
xp.general.cap_max_xp_level=true
# Maximum player level.
xp.general.xp_max_level=100


# [XP]

# [GENERAL]
# Chance for an Enchanted Tome to appear in epic loot chests.
loot.general.epic_loot_chance=0.8
# Chance for an Enchanted Tome to appear in rare loot chests.
loot.general.rare_loot_chance=0.45
# Chance for an Enchanted Tome to appear in uncommon loot chests.
loot.general.uncommon_loot_chance=0.2
# Chance for an Enchanted Tome to appear in common loot chests.
loot.general.common_loot_chance=0.05


# [LOOT]

# [ENCHANTING_TABLE]
# Whether the enchanting table buttons should be plain or textured.
accessibility.enchanting_table.use_plain_background=false
# Whether the enchanting table should show new enchantments in the standard galactic alphabet.
accessibility.enchanting_table.obfuscate_new_enchantments=true

# [ENCHANTMENT_NAME]
# Whether enchantment names should not be colored according to their assigned theme.
accessibility.enchantment_name.override_enchantment_name_color=false
# The color value enchantment names should be override with.
accessibility.enchantment_name.enchantment_name_color_override_value=16777215

# [ENCHANTMENT_LEVEL]
# Whether enchantment levels should not be colored depending on their value.
accessibility.enchantment_level.override_enchantment_level_color=false
# The color value enchantment levels should be override with.
accessibility.enchantment_level.enchantment_level_color_override_value=16777215

# [ENCHANTMENT_TOOLTIP]
# Whether the enchantment tooltip block header should be colored uniformly.
accessibility.enchantment_tooltip.override_enchantment_header_color=false
# The color value enchantment tooltips headers should be overridden with.
accessibility.enchantment_tooltip.enchantment_level_color_override_value=16777215

# [ENCHANTMENT_DESCRIPTION]
# The color value enchantment descriptions should be override with.
accessibility.enchantment_description.enchantment_description_color_value=10987431


# [ACCESSIBILITY]
